spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.232.131/sell?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
env: dev

